<?php
    $title = 'Locations';
    $this->headTitle($title);
?>
    
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <a href="<?= $this->url('local', ['action' => 'add']) ?>">Add new local</a>
</p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>Type</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $local) : ?>
    <tr>
        <td><?= $this->escapeHtml($local->id) ?></td>
        <td><?= $this->escapeHtml($local->name) ?></td>
        <td><?= $this->escapeHtml($local->type_name) ?></td>
        <td>
            <a href="<?= $this->url('local', ['action' => 'edit', 'id' => $local->id]) ?>">Edit</a>
            <a href="<?= $this->url('local', ['action' => 'delete', 'id' => $local->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<!-- view helpers para exibir paginacao -->
<?= $this->paginationControl(

        // objeto paginator
        $this->paginator,

        // tipo de scroll
        'sliding',

        // partial para usar para renderizar o control
        'partial/paginator',

        // rota para quando o usuario clicar num link de control
        ['route' => 'local'] // indexAction
    ) 
?> 