<?php
    $title = 'Location Types';
    $this->headTitle($title);
?>
    
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <a href="<?= $this->url('localtype', ['action' => 'add']) ?>">Add new local type</a>
</p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $type) : ?>
    <tr>
        <td><?= $this->escapeHtml($type->id) ?></td>
        <td><?= $this->escapeHtml($type->name) ?></td>
        <td>
            <a href="<?= $this->url('localtype', ['action' => 'edit', 'id' => $type->id]) ?>">Edit</a>
            <a href="<?= $this->url('localtype', ['action' => 'delete', 'id' => $type->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<?= $this->paginationControl(

        // objeto paginator
        $this->paginator,

        // tipo de scroll
        'sliding',

        // partial para usar para renderizar o control
        'partial/paginator',

        // rota para quando o usuario clicar num link de control
        ['route' => 'localtype'] // indexAction
    ) 
?> 
